version: '3'
services:
  docker-socket-proxy:
    build: .
    image: thomaspetit/docker-socket-proxy
    volumes:
      - "./server-keys:/server-keys:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      CERTS_DIR: "/server-keys"
    ports:
      - "2376:2376"
    command: ["-dd", "-lmlocal2"]
    restart: always
